=== mploschiavo/contact-transmutator/contact-transmut/InternalDoc.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xsd:element name="root" type="rootType" />

<xsd:complexType name="rootType">
    <xsd:sequence>
        <xsd:element name="person" minOccurs="0" maxOccurs="unbounded" type="personType" />
    </xsd:sequence>
    <xsd:attribute name="maxColumnNumber" type="xsd:int" />
</xsd:complexType>

<xsd:complexType name="personType">
    <xsd:sequence>
        <xsd:element name="uncategorized" minOccurs="1" maxOccurs="1" type="uncatType" />
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="uncatType">
    <xsd:sequence>
        <xsd:element name="data" minOccurs="1" maxOccurs="unbounded" type="dataType" />
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="dataType">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute name="counter" type="xsd:int" />
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

</xsd:schema>

=== mploschiavo/contact-transmutator/contact-transmut/InternalDoc.xml
<?xml version="1.0" encoding="UTF-8"?>

<root   xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation="InternalDoc.xsd"
        maxColumnNumber="3">
    <person>
        <uncategorized>
            <data counter="0">Name</data>
            <data counter="1">Formatted_Name</data>
            <data counter="2">1990-05-14</data>
        </uncategorized>
    </person>
    <person>
        <uncategorized>
            <data counter="0"/>
            <data counter="1">Formatted_Name</data>
            <data counter="2"/>
        </uncategorized>
    </person>
</root>
